a=input("Enter ur Name :")
b=input("Enter ur Phone no :")
print("Enter Ur dob")
c=input("date")
d=input("month")
e=input("year")
email=input("Email")

print("\nName",a,"\nPhone",b,"\nEmail",email)
print("Dob is : ",c,"/",d,"/",e)
